// 80 skins from the weapon sheet; rarity from the sheet border, price deterministic per name.
const images = import.meta.glob("../assets/guns/*.png", { eager: true, import: "default" }) as Record<string, string>;

export type Gun = {
  name: string;
  price: number;
  rarity: "Mil-Spec" | "Restricted" | "Classified" | "Covert" | "Gold";
  image: string;
};

export const GUNS: Gun[] = [
  { name: 'AK-47 | Redline', price: 8.85, rarity: 'Mil-Spec', image: images['../assets/guns/ak-47-redline.png'] ?? '' },
  { name: 'AK-47 | Ice Coaled', price: 50.0, rarity: 'Restricted', image: images['../assets/guns/ak-47-ice-coaled.png'] ?? '' },
  { name: 'AK-47 | Fire Serpent', price: 22.46, rarity: 'Mil-Spec', image: images['../assets/guns/ak-47-fire-serpent.png'] ?? '' },
  { name: 'AK-47 | Neon Revolution', price: 10.41, rarity: 'Mil-Spec', image: images['../assets/guns/ak-47-neon-revolution.png'] ?? '' },
  { name: 'AK-47 | Case Hardened', price: 9.4, rarity: 'Mil-Spec', image: images['../assets/guns/ak-47-case-hardened.png'] ?? '' },
  { name: 'AK-47 | Vulcan', price: 21.08, rarity: 'Mil-Spec', image: images['../assets/guns/ak-47-vulcan.png'] ?? '' },
  { name: 'AK-47 | Wasteland Rebel', price: 18.31, rarity: 'Mil-Spec', image: images['../assets/guns/ak-47-wasteland-rebel.png'] ?? '' },
  { name: 'AK-47 | Frontside Misty', price: 82.13, rarity: 'Restricted', image: images['../assets/guns/ak-47-frontside-misty.png'] ?? '' },
  { name: 'AK-47 | Jaguar', price: 1831.83, rarity: 'Gold', image: images['../assets/guns/ak-47-jaguar.png'] ?? '' },
  { name: 'AK-47 | Point Disarray', price: 14.68, rarity: 'Mil-Spec', image: images['../assets/guns/ak-47-point-disarray.png'] ?? '' },
  { name: 'M4A1-S | Printstream', price: 21.0, rarity: 'Mil-Spec', image: images['../assets/guns/m4a1-s-printstream.png'] ?? '' },
  { name: 'M4A1-S | Blue Phosphor', price: 16.69, rarity: 'Mil-Spec', image: images['../assets/guns/m4a1-s-blue-phosphor.png'] ?? '' },
  { name: 'M4A1-S | Hyper Beast', price: 256.96, rarity: 'Classified', image: images['../assets/guns/m4a1-s-hyper-beast.png'] ?? '' },
  { name: "M4A1-S | Chantico's Fire", price: 888.59, rarity: 'Covert', image: images['../assets/guns/m4a1-s-chanticos-fire.png'] ?? '' },
  { name: 'M4A1-S | Nightmare', price: 87.6, rarity: 'Restricted', image: images['../assets/guns/m4a1-s-nightmare.png'] ?? '' },
  { name: 'M4A1-S | Leaded Glass', price: 779.98, rarity: 'Covert', image: images['../assets/guns/m4a1-s-leaded-glass.png'] ?? '' },
  { name: 'M4A1-S | Mecha Industries', price: 8.87, rarity: 'Mil-Spec', image: images['../assets/guns/m4a1-s-mecha-industries.png'] ?? '' },
  { name: 'M4A1-S | Player Two', price: 36.97, rarity: 'Restricted', image: images['../assets/guns/m4a1-s-player-two.png'] ?? '' },
  { name: 'M4A1-S | Golden Coil', price: 2304.9, rarity: 'Gold', image: images['../assets/guns/m4a1-s-golden-coil.png'] ?? '' },
  { name: 'M4A1-S | Dark Water', price: 16.01, rarity: 'Mil-Spec', image: images['../assets/guns/m4a1-s-dark-water.png'] ?? '' },
  { name: 'AWP | Asiimov', price: 19.21, rarity: 'Mil-Spec', image: images['../assets/guns/awp-asiimov.png'] ?? '' },
  { name: 'AWP | Dragon Lore', price: 16.91, rarity: 'Mil-Spec', image: images['../assets/guns/awp-dragon-lore.png'] ?? '' },
  { name: 'AWP | Hyper Beast', price: 101.8, rarity: 'Classified', image: images['../assets/guns/awp-hyper-beast.png'] ?? '' },
  { name: 'AWP | Medusa', price: 6.47, rarity: 'Mil-Spec', image: images['../assets/guns/awp-medusa.png'] ?? '' },
  { name: 'AWP | Electric Hive', price: 81.35, rarity: 'Restricted', image: images['../assets/guns/awp-electric-hive.png'] ?? '' },
  { name: 'AWP | Redline', price: 382.68, rarity: 'Covert', image: images['../assets/guns/awp-redline.png'] ?? '' },
  { name: 'AWP | Chromatic Aberration', price: 117.22, rarity: 'Classified', image: images['../assets/guns/awp-chromatic-aberration.png'] ?? '' },
  { name: 'AWP | BOOM', price: 1915.22, rarity: 'Gold', image: images['../assets/guns/awp-boom.png'] ?? '' },
  { name: 'AWP | Safari Mesh', price: 3051.95, rarity: 'Gold', image: images['../assets/guns/awp-safari-mesh.png'] ?? '' },
  { name: 'AWP | Graphite', price: 12.42, rarity: 'Mil-Spec', image: images['../assets/guns/awp-graphite.png'] ?? '' },
  { name: 'Desert Eagle | Printstream', price: 19.91, rarity: 'Mil-Spec', image: images['../assets/guns/desert-eagle-printstream.png'] ?? '' },
  { name: 'Desert Eagle | Blaze', price: 1736.54, rarity: 'Gold', image: images['../assets/guns/desert-eagle-blaze.png'] ?? '' },
  { name: 'Desert Eagle | Cobalt Disruption', price: 18.27, rarity: 'Mil-Spec', image: images['../assets/guns/desert-eagle-cobalt-disruption.png'] ?? '' },
  { name: 'Desert Eagle | Conspiracy', price: 75.35, rarity: 'Restricted', image: images['../assets/guns/desert-eagle-conspiracy.png'] ?? '' },
  { name: 'Desert Eagle | Kumicho Dragon', price: 40.93, rarity: 'Restricted', image: images['../assets/guns/desert-eagle-kumicho-dragon.png'] ?? '' },
  { name: 'Desert Eagle | Code Red', price: 983.88, rarity: 'Covert', image: images['../assets/guns/desert-eagle-code-red.png'] ?? '' },
  { name: 'Desert Eagle | Fennec Fox', price: 2420.62, rarity: 'Gold', image: images['../assets/guns/desert-eagle-fennec-fox.png'] ?? '' },
  { name: 'Desert Eagle | Directive', price: 84.95, rarity: 'Restricted', image: images['../assets/guns/desert-eagle-directive.png'] ?? '' },
  { name: 'Desert Eagle | Night Heist', price: 18.11, rarity: 'Mil-Spec', image: images['../assets/guns/desert-eagle-night-heist.png'] ?? '' },
  { name: 'Desert Eagle | Golden Koi', price: 10.7, rarity: 'Mil-Spec', image: images['../assets/guns/desert-eagle-golden-koi.png'] ?? '' },
  { name: 'USP-S | Kill Confirmed', price: 16.65, rarity: 'Mil-Spec', image: images['../assets/guns/usp-s-kill-confirmed.png'] ?? '' },
  { name: 'USP-S | Blueprint', price: 20.05, rarity: 'Mil-Spec', image: images['../assets/guns/usp-s-blueprint.png'] ?? '' },
  { name: 'USP-S | Orion', price: 2669.07, rarity: 'Gold', image: images['../assets/guns/usp-s-orion.png'] ?? '' },
  { name: 'USP-S | Neo-Noir', price: 61.29, rarity: 'Restricted', image: images['../assets/guns/usp-s-neo-noir.png'] ?? '' },
  { name: 'USP-S | The Traitor', price: 818.52, rarity: 'Covert', image: images['../assets/guns/usp-s-the-traitor.png'] ?? '' },
  { name: 'USP-S | Cortex', price: 178.08, rarity: 'Classified', image: images['../assets/guns/usp-s-cortex.png'] ?? '' },
  { name: 'USP-S | Road Rash', price: 10.16, rarity: 'Mil-Spec', image: images['../assets/guns/usp-s-road-rash.png'] ?? '' },
  { name: 'USP-S | Torque', price: 109.01, rarity: 'Classified', image: images['../assets/guns/usp-s-torque.png'] ?? '' },
  { name: 'USP-S | Monster Mashup', price: 15.64, rarity: 'Mil-Spec', image: images['../assets/guns/usp-s-monster-mashup.png'] ?? '' },
  { name: 'USP-S | Royal Blue', price: 14.04, rarity: 'Mil-Spec', image: images['../assets/guns/usp-s-royal-blue.png'] ?? '' },
  { name: 'P90 | Asiimov', price: 14.04, rarity: 'Mil-Spec', image: images['../assets/guns/p90-asiimov.png'] ?? '' },
  { name: 'P90 | Shapewood', price: 2454.65, rarity: 'Gold', image: images['../assets/guns/p90-shapewood.png'] ?? '' },
  { name: 'P90 | Death by Kitty', price: 4.81, rarity: 'Mil-Spec', image: images['../assets/guns/p90-death-by-kitty.png'] ?? '' },
  { name: 'P90 | Cold Blooded', price: 211.71, rarity: 'Classified', image: images['../assets/guns/p90-cold-blooded.png'] ?? '' },
  { name: 'P90 | Emerald Dragon', price: 132.43, rarity: 'Classified', image: images['../assets/guns/p90-emerald-dragon.png'] ?? '' },
  { name: 'P90 | Module', price: 17.98, rarity: 'Mil-Spec', image: images['../assets/guns/p90-module.png'] ?? '' },
  { name: 'P90 | Grim', price: 225.53, rarity: 'Classified', image: images['../assets/guns/p90-grim.png'] ?? '' },
  { name: 'P90 | Scarab', price: 1539.14, rarity: 'Gold', image: images['../assets/guns/p90-scarab.png'] ?? '' },
  { name: 'P90 | Traction', price: 13.98, rarity: 'Mil-Spec', image: images['../assets/guns/p90-traction.png'] ?? '' },
  { name: 'P90 | Blind Spot', price: 17.72, rarity: 'Mil-Spec', image: images['../assets/guns/p90-blind-spot.png'] ?? '' },
  { name: 'MP7 | Bloodsport', price: 8.36, rarity: 'Mil-Spec', image: images['../assets/guns/mp7-bloodsport.png'] ?? '' },
  { name: 'MP7 | Abyssal Apparition', price: 19.91, rarity: 'Mil-Spec', image: images['../assets/guns/mp7-abyssal-apparition.png'] ?? '' },
  { name: 'MP7 | Neon Rider', price: 13.06, rarity: 'Mil-Spec', image: images['../assets/guns/mp7-neon-rider.png'] ?? '' },
  { name: 'MP7 | Just Smile', price: 205.31, rarity: 'Classified', image: images['../assets/guns/mp7-just-smile.png'] ?? '' },
  { name: 'MP7 | Fade', price: 2749.05, rarity: 'Gold', image: images['../assets/guns/mp7-fade.png'] ?? '' },
  { name: 'MP7 | Cirrus', price: 21.14, rarity: 'Mil-Spec', image: images['../assets/guns/mp7-cirrus.png'] ?? '' },
  { name: 'MP7 | Ivory', price: 19.89, rarity: 'Mil-Spec', image: images['../assets/guns/mp7-ivory.png'] ?? '' },
  { name: 'MP7 | Forest DDPAT', price: 16.53, rarity: 'Mil-Spec', image: images['../assets/guns/mp7-forest-ddpat.png'] ?? '' },
  { name: 'MP7 | Ocean Foam', price: 22.31, rarity: 'Mil-Spec', image: images['../assets/guns/mp7-ocean-foam.png'] ?? '' },
  { name: 'MP7 | Special Delivery', price: 13.41, rarity: 'Mil-Spec', image: images['../assets/guns/mp7-special-delivery.png'] ?? '' },
  { name: 'Nova | Hyper Beast', price: 20.14, rarity: 'Mil-Spec', image: images['../assets/guns/nova-hyper-beast.png'] ?? '' },
  { name: 'Nova | Wood Fired', price: 42.61, rarity: 'Restricted', image: images['../assets/guns/nova-wood-fired.png'] ?? '' },
  { name: 'Nova | Wild Six', price: 2274.27, rarity: 'Gold', image: images['../assets/guns/nova-wild-six.png'] ?? '' },
  { name: 'Nova | Rising Sun', price: 131.23, rarity: 'Classified', image: images['../assets/guns/nova-rising-sun.png'] ?? '' },
  { name: 'Nova | Tempest', price: 20.16, rarity: 'Mil-Spec', image: images['../assets/guns/nova-tempest.png'] ?? '' },
  { name: 'Nova | Polar Mesh', price: 14.27, rarity: 'Mil-Spec', image: images['../assets/guns/nova-polar-mesh.png'] ?? '' },
  { name: 'Nova | Bloomstick', price: 19.97, rarity: 'Mil-Spec', image: images['../assets/guns/nova-bloomstick.png'] ?? '' },
  { name: 'Nova | Green Apple', price: 9.32, rarity: 'Mil-Spec', image: images['../assets/guns/nova-green-apple.png'] ?? '' },
  { name: 'Nova | Moon in Libra', price: 13.96, rarity: 'Mil-Spec', image: images['../assets/guns/nova-moon-in-libra.png'] ?? '' },
  { name: 'Nova | Predator', price: 23.48, rarity: 'Mil-Spec', image: images['../assets/guns/nova-predator.png'] ?? '' },
];
